---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - USER=admin
      - PASS=qwerty12
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ~/qbittorrent/config:/config
      - /anonymous/files/downloads:/downloads
    ports:
      - 11080:8080
      - 16881:6881
      - 16881:6881/udp
    restart: unless-stopped
