# Example 2
#
# Single box with VirtualBox provider.
#
# NOTE: Make sure you have the precise32 base box installed...
# vagrant box add precise32 http://files.vagrantup.com/precise32.box
#
# VirtualBox modifyvm docs: http://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.hostname = "centos8vb"
  config.vm.network :public_network
  config.vm.provider "virtualbox"

  # config.vm.provider :virtualbox do |vb|
  #   vb.customize [
  #     "modifyvm", :id,
  #     "--cpuexecutioncap", "50",
  #     "--memory", "256",
  #   ]
  # end
end
