Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.hostname = "debian11"
    config.vm.network :public_network, ip: "192.168.88.109"
    config.vm.provider "virtualbox"
  
    # config.vm.provider :virtualbox do |vb|
    #   vb.customize [
    #     "modifyvm", :id,
    #     "--cpuexecutioncap", "50",
    #     "--memory", "256",
    #   ]
    # end
  end