Vagrant.configure("2") do |config|
    config.vm.box = "fedora/35-cloud-base"
    config.vm.box_version = "35.20211026.0"
    config.vm.hostname = "fedora35"
    config.vm.network :public_network
    config.vm.provider "virtualbox"
  
    # config.vm.provider :virtualbox do |vb|
    #   vb.customize [
    #     "modifyvm", :id,
    #     "--cpuexecutioncap", "50",
    #     "--memory", "256",
    #   ]
    # end
  end