nodes = [
  { :hostname => 'debian11-swarm-node1', :ip => '192.168.88.110', :box => 'debian/bullseye64' },
  { :hostname => 'debian11-swarm-node2', :ip => '192.168.88.111', :box => 'debian/bullseye64' }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "debian/bullseye64"
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network :public_network, ip: node[:ip]
    end
  end

#   config.vm.provision :puppet do |puppet|
#     puppet.manifests_path = "puppet/manifests"
#     puppet.manifest_file = "site.pp"
#     puppet.module_path = "puppet/modules"
#   end
end
