nodes = [
  { :hostname => 'debian11-k3s-m1', :ip => '192.168.88.50', :box => 'debian/bullseye64', :memory=> '2048' },
  { :hostname => 'debian11-k3s-m2', :ip => '192.168.88.51', :box => 'debian/bullseye64', :memory=> '2048' },
  { :hostname => 'debian11-k3s-m3', :ip => '192.168.88.52', :box => 'debian/bullseye64', :memory=> '2048' },
  { :hostname => 'debian11-k3s-w1', :ip => '192.168.88.53', :box => 'debian/bullseye64', :memory=> '2048' }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "debian/bullseye64"
    # nodeconfig.vm.memory = "2048" why don't work?
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network :public_network, ip: node[:ip], bridge: 'wlx503eaab9d385'
    end
   end
   config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  
   config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
   end

#   config.vm.provision :puppet do |puppet|
#     puppet.manifests_path = "puppet/manifests"
#     puppet.manifest_file = "site.pp"
#     puppet.module_path = "puppet/modules"
#   end
end
